<?php

define("IN_SITE", true);
require_once __DIR__ . "/libs/db.php";
require_once __DIR__ . "/config.php";
require_once __DIR__ . "/libs/lang.php";
require_once __DIR__ . "/libs/helper.php";
require_once __DIR__ . "/libs/database/users.php";
$CMSNT = new DB();
echo "<meta name=\"robots\" content=\"noindex\">\n<title>Version</title>\n<style>\n    table {\n        width: 100%;\n        border-collapse: collapse;\n    }\n\n    th, td {\n        border: 1px solid black;\n        padding: 8px;\n        text-align: left;\n    }\n\n    th {\n        background-color: #f2f2f2;\n    }\n\n    tr:hover {\n        background-color: #f5f5f5; /* Màu nền khi hover */\n    }\n\n    th:hover {\n        background-color: #ddd; /* Màu nền khi hover trên header */\n    }\n\n    td:hover {\n        background-color: #eaeaea; /* Màu nền khi hover trên cell */\n    }\n</style>\n</head>\n<body>\n\n<h2>Thông tin hệ thống</h2>\n\n<table>\n    <tbody>\n        <tr>\n            <td>Project</td>\n            <td><b>";
echo $config["project"];
echo "</b></td>\n        </tr>\n        <tr>\n            <td>Phiên bản cập nhật</td>\n            <td><b style=\"color:red;\">";
echo $config["version"];
echo "</b></td>\n        </tr>\n        <tr>\n            <td>Tự động cập nhật phiên bản</td>\n            <td><b>";
echo $CMSNT->site("status_update") == 1 ? "<span style=\"color:green;\">ON</span>" : "<span style=\"color:red;\">OFF</span>";
echo "</b></td>\n        </tr>\n        <tr>\n            <td>SMTP</td>\n            <td><b>";
echo $CMSNT->site("smtp_status") == 1 ? "<span style=\"color:green;\">ON</span>" : "<span style=\"color:red;\">OFF</span>";
echo "</b></td>\n        </tr>\n        <tr>\n            <td>Debug Auto Bank</td>\n            <td><b>";
echo $CMSNT->site("debug_auto_bank") == 1 ? "<span style=\"color:green;\">ON</span>" : "<span style=\"color:red;\">OFF</span>";
echo "</b></td>\n        </tr>\n        <tr>\n            <td>Debug API Suppliers</td>\n            <td><b>";
echo $CMSNT->site("debug_api_suppliers") == 1 ? "<span style=\"color:green;\">ON</span>" : "<span style=\"color:red;\">OFF</span>";
echo "</b></td>\n        </tr>\n        <tr>\n            <td>Phiên bản PHP</td>\n            <td><b style=\"color:blue;\">";
echo phpversion();
echo "</b></td>\n        </tr>\n        <tr>\n            <td colspan=\"2\" style=\"background-color: black;color:white;\">Settings</td>\n        </tr>\n        <tr>\n            <td>Số tiền nạp Bank tối thiểu</td>\n            <td><b>";
echo format_currency($CMSNT->site("bank_min"));
echo "</b></td>\n        </tr>\n        <tr>\n            <td>Số tiền nạp Bank tối đa</td>\n            <td><b>";
echo format_currency($CMSNT->site("bank_max"));
echo "</b></td>\n        </tr>\n        <tr>\n            <td>Prefix</td>\n            <td><b>";
echo $CMSNT->site("prefix_autobank");
echo "{id}</b></td>\n        </tr>\n        <tr>\n            <td colspan=\"2\" style=\"background-color: black;color:white;\">PHP Options</td>\n        </tr>\n        <tr>\n            <td>display_errors</td>\n            <td><b>";
echo ini_get("display_errors") ? "<span style=\"color:green;\">ON</span>" : "<span style=\"color:red;\">OFF</span>";
echo "</b></td>\n        </tr>\n        <tr>\n            <td>allow_url_fopen</td>\n            <td><b>";
echo ini_get("allow_url_fopen") ? "<span style=\"color:green;\">ON</span>" : "<span style=\"color:red;\">OFF</span>";
echo "</b></td>\n        </tr>\n        <tr>\n            <td>log_errors</td>\n            <td><b>";
echo ini_get("log_errors") ? "<span style=\"color:green;\">ON</span>" : "<span style=\"color:red;\">OFF</span>";
echo "</b></td>\n        </tr>\n        <tr>\n            <td>max_execution_time</td>\n            <td><b>";
echo ini_get("max_execution_time");
echo "</b></td>\n        </tr>\n        <tr>\n            <td>memory_limit</td>\n            <td><b>";
echo ini_get("memory_limit");
echo "</b></td>\n        </tr>\n        <tr>\n            <td>upload_max_filesize</td>\n            <td><b>";
echo ini_get("upload_max_filesize");
echo "</b></td>\n        </tr>\n        <tr>\n            <td colspan=\"2\" style=\"background-color: black;color:white;\">PHP Extension</td>\n        </tr>\n        <tr>\n            <td>Extension calendar</td>\n            <td><b>";
echo extension_loaded("calendar") ? "<span style=\"color:green;\">ON</span>" : "<span style=\"color:red;\">OFF</span>";
echo "</b></td>\n        </tr>\n        <tr>\n            <td>Extension zip</td>\n            <td><b>";
echo extension_loaded("zip") ? "<span style=\"color:green;\">ON</span>" : "<span style=\"color:red;\">OFF</span>";
echo "</b></td>\n        </tr>\n        <tr>\n            <td>Extension gmagick</td>\n            <td><b>";
echo extension_loaded("gmagick") ? "<span style=\"color:green;\">ON</span>" : "<span style=\"color:red;\">OFF</span>";
echo "</b></td>\n        </tr>\n        <tr>\n            <td>Extension mbstring</td>\n            <td><b>";
echo extension_loaded("mbstring") ? "<span style=\"color:green;\">ON</span>" : "<span style=\"color:red;\">OFF</span>";
echo "</b></td>\n        </tr>\n        <tr>\n            <td colspan=\"2\" style=\"background-color: black;color:white;\">Cron Jobs</td>\n        </tr>\n        <tr>\n            <td>";
echo base_url("cron/bank.php");
echo "</td>\n            <td><b>";
echo timeAgo($CMSNT->site("check_time_cron_bank"));
echo "</b></td>\n        </tr>\n        <tr>\n            <td>";
echo base_url("cron/momo.php");
echo "</td>\n            <td><b>";
echo timeAgo($CMSNT->site("check_time_cron_momo"));
echo "</b></td>\n        </tr>\n        <tr>\n            <td>";
echo base_url("cron/task.php");
echo "</td>\n            <td><b>";
echo timeAgo($CMSNT->site("check_time_cron_task"));
echo "</b></td>\n        </tr>\n        <tr>\n            <td>";
echo base_url("cron/sending_email.php");
echo "</td>\n            <td><b>";
echo timeAgo($CMSNT->site("check_time_cron_sending_email"));
echo "</b></td>\n        </tr>\n        <tr>\n            <td>";
echo base_url("cron/cron.php");
echo "</td>\n            <td><b>";
echo timeAgo($CMSNT->site("check_time_cron_cron"));
echo "</b></td>\n        </tr>\n        <tr>\n            <td>";
echo base_url("cron/checklive/clone.php");
echo "</td>\n            <td><b>";
echo timeAgo($CMSNT->site("time_cron_checklive_clone"));
echo "</b></td>\n        </tr>\n        <tr>\n            <td>";
echo base_url("cron/checklive/hotmail.php");
echo "</td>\n            <td><b>";
echo timeAgo($CMSNT->site("time_cron_checklive_hotmail"));
echo "</b></td>\n        </tr>\n        <tr>\n            <td>";
echo base_url("cron/suppliers/shopclone6.php");
echo "</td>\n            <td><b>";
echo timeAgo($CMSNT->site("time_cron_suppliers_shopclone6"));
echo "</b></td>\n        </tr>\n        <tr>\n            <td>";
echo base_url("cron/suppliers/shopclone7.php");
echo "</td>\n            <td><b>";
echo timeAgo($CMSNT->site("time_cron_suppliers_shopclone7"));
echo "</b></td>\n        </tr>\n        <tr>\n            <td>";
echo base_url("cron/suppliers/api1.php");
echo "</td>\n            <td><b>";
echo timeAgo($CMSNT->site("time_cron_suppliers_api1"));
echo "</b></td>\n        </tr>\n        <tr>\n            <td>";
echo base_url("cron/suppliers/api4.php");
echo "</td>\n            <td><b>";
echo timeAgo($CMSNT->site("time_cron_suppliers_api4"));
echo "</b></td>\n        </tr>\n        <tr>\n            <td>";
echo base_url("cron/suppliers/api6.php");
echo "</td>\n            <td><b>";
echo timeAgo($CMSNT->site("time_cron_suppliers_api6"));
echo "</b></td>\n        </tr>\n        <tr>\n            <td>";
echo base_url("cron/suppliers/api14.php");
echo "</td>\n            <td><b>";
echo timeAgo($CMSNT->site("time_cron_suppliers_api14"));
echo "</b></td>\n        </tr>\n        <tr>\n            <td>";
echo base_url("cron/suppliers/api17.php");
echo "</td>\n            <td><b>";
echo timeAgo($CMSNT->site("time_cron_suppliers_api17"));
echo "</b></td>\n        </tr>\n        <tr>\n            <td>";
echo base_url("cron/suppliers/api18.php");
echo "</td>\n            <td><b>";
echo timeAgo($CMSNT->site("time_cron_suppliers_api18"));
echo "</b></td>\n        </tr>\n        <tr>\n            <td>";
echo base_url("cron/suppliers/api19.php");
echo "</td>\n            <td><b>";
echo timeAgo($CMSNT->site("time_cron_suppliers_api19"));
echo "</b></td>\n        </tr>\n        <tr>\n            <td>";
echo base_url("cron/suppliers/api20.php");
echo "</td>\n            <td><b>";
echo timeAgo($CMSNT->site("time_cron_suppliers_api20"));
echo "</b></td>\n        </tr>\n        <tr>\n            <td>";
echo base_url("cron/suppliers/api21.php");
echo "</td>\n            <td><b>";
echo timeAgo($CMSNT->site("time_cron_suppliers_api21"));
echo "</b></td>\n        </tr>\n        <tr>\n            <td>";
echo base_url("cron/suppliers/api22.php");
echo "</td>\n            <td><b>";
echo timeAgo($CMSNT->site("time_cron_suppliers_api22"));
echo "</b></td>\n        </tr>\n    </tbody>\n</table>\n\n</body>\n</html>\n";

?>